{% set version = "2.4.0" %}

package:
  name: tensorflow
  version: {{ version }}

source:
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz
  sha256: 26c833b7e1873936379e810a39d14700281125257ddda8cd822c89111db6f6ae

  patches:
    - patches/0001-relax-tolerence-in-special_math_test.patch
    - patches/0002-skip-read-only-debugger_cli_common-test.patch
    - patches/0003-relax-precision-in-matrix_log_op_test.patch
    - patches/0004-Unbundle-LLVM.patch
    - patches/0005-rerun-generate_llvm_build.py.patch

build:
  number: 0
  skip: true  # [win or py<38]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # see https://github.com/tensorflow/tensorflow/blob/v{{ version }}/.bazelversion
    - bazel ==3.1.0
    - nasm
  host:
    # conda build requirements
    - python
    - pip
    # TODO: potentially remove these?
    - llvmdev >=9.0.0
    - zlib
    - libpng
    - libcurl
    - curl         # [win]
    - unzip        # [not win]
    - zip          # [not win]
    - m2-unzip     # [win]
    - m2-zip       # [win]
    - openjdk >=8
    - nsync
    # requirements specified by the package itself, see
    # github.com/tensorflow/tensorflow/blob/v{{ version }}/tensorflow/tools/pip_package/setup.py
    - absl-py >=0.10.0
    - astunparse >=1.6.3
    - python-flatbuffers >=1.12.0
    - google-pasta >=0.2
    - h5py >=2.10
    - keras-preprocessing >=1.1.2
    - numpy >=1.19.2
    - opt_einsum >=3.3.0
    - protobuf >=3.9.2
    - six >=1.15.0
    - termcolor >=1.1.0
    - typing_extensions >=3.7.4
    - wheel >=0.35
    - wrapt >=1.11.1
    # TF_SYSTEM_LIBS
    - astor >=0.7.1
    - grpc-cpp
    - libprotobuf
    - giflib
    - libjpeg-turbo
    - openssl
    - cython >=0.28.4
    - dill >=0.3.1.1
    - snappy
    # upstream wants exact pin for gast
    - gast ==0.3.3
    # TF-API needs to move in sync
    - tensorboard >=2.4.0,<2.5
    - tensorflow-estimator >=2.4.0,<2.5
  #run:
  #- {{ pin_subpackage('tensorflow-base', exact=True) }}

outputs:
  - name: tensorflow-base
    script: build_pkg.sh  # [not win]
    script: build_pkg.bat  # [win]
    build:
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      host:
        # conda build requirements
        - python
        - pip
        # requirements specified by the package itself
        - absl-py >=0.10.0
        - astunparse >=1.6.3
        - python-flatbuffers >=1.12.0
        - google-pasta >=0.2
        - h5py >=2.10
        - keras-preprocessing >=1.1.2
        - numpy >=1.19.2
        - opt_einsum >=3.3.0
        - protobuf >=3.9.2
        - six >=1.15.0
        - termcolor >=1.1.0
        - typing_extensions >=3.7.4
        - wheel >=0.35
        - wrapt >=1.11.1
        # upstream wants exact pin for gast
        - gast ==0.3.3
        # TF-API needs to move in sync
        - tensorboard >=2.4.0,<2.5
        - tensorflow-estimator >=2.4.0,<2.5
      run:
        - python
        - absl-py >=0.10.0
        - astunparse >=1.6.3
        - python-flatbuffers >=1.12.0
        - google-pasta >=0.2
        - h5py >=2.10
        - keras-preprocessing >=1.1.2
        - numpy >=1.19.2
        - opt_einsum >=3.3.0
        - protobuf >=3.9.2
        - six >=1.15.0
        - termcolor >=1.1.0
        - typing_extensions >=3.7.4
        - wheel >=0.35
        - wrapt >=1.11.1
        # upstream wants exact pin for gast
        - gast ==0.3.3
        # TF-API needs to move in sync
        - tensorboard >=2.4.0,<2.5
        - tensorflow-estimator >=2.4.0,<2.5
    test:
      imports:
        - tensorflow
      commands:
        - tf_upgrade_v2 --help
        - saved_model_cli --help
        - tflite_convert --help     # [not win]
        - toco_from_protos --help   # [not win]
        - toco --help               # [not win]

  - name: libtensorflow
    script: cp_libtensorflow.sh
    build:
      skip: true                    # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
      # host requirements to pick up run_exports
      host:
        - libcurl
        - zlib

    test:
      files:
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win]
        - $CC -o test_c -L${PREFIX}/lib/ -ltensorflow -I${PREFIX}/include/ test_c.c && ./test_c  # [not win]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh
    build:
      skip: true                    # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - rsync
      # host requirements to pick up run_exports
      host:
        - libcurl
        - zlib
    test:
      files:
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
        - $CXX -std=c++11 -o test_cc -L${PREFIX}/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I${PREFIX}/include/ test_cc.cc && ./test_cc  # [not win]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  feedstock-name: tensorflow
  recipe-maintainers:
    - waitingkuo
    - ghego
    - hajapy
    - gilbertfrancois
    - farhantejani
    - njzjz
    - jschueller
