{% set version = "2.2.0" %}

{% set pyver = "cp{}{}".format(PY_VER[0], PY_VER[2]) %}
{% set platform = "macosx_10_11_x86_64" %}  # [osx] 
{% set platform = "win_amd64" %}  # [win]
{% set fn = "{}-{}-{}-{}m-{}.whl".format("tensorflow", version, pyver, pyver, platform) %}  # [not linux]
{% set fn = "tensorflow-{{ version }}.tar.gz" %}  # [linux]

package:
  name: tensorflow
  version: {{ version }}

source:
  fn: {{ fn }}
  url: https://github.com/tensorflow/tensorflow/archive/v{{ version }}.tar.gz  # [linux]
  sha256: 69cd836f87b8c53506c4f706f655d423270f5a563b76dc1cfa60fbc3184185a3  # [linux]
  url: https://pypi.io/packages/{{ pyver }}/t/tensorflow/{{ fn }}  # [not linux]
  sha256: 6735486ee9c3cb0807476e2b36ef7a4cd6c597cb24abf496e66b703360e1e54e  # [osx and py==36]
  sha256: c332c7fc5cfd54cb86d5da99787c9693e3a924848097c54df1b71ee595a39c93  # [osx and py==37]
  sha256: bbcfb04738099bd46822db91584db74703fdddacf4cd0a76acfc5e086956b5ba  # [osx and py==38]
  sha256: 3ee8819732d8594913b7d22ded7b22e48a49aa015050d8dd8464eaa010ba2e41  # [win and py==36]
  sha256: 68ea22aee9c269a6a0c1061c141f1ec1cd1b1be7569390519c1bf4773f434a40  # [win and py==37]
  sha256: 784ab8217e4b0eb4d121c28430c6cdc2ce56c02634a9720d84fb30598b338b8c  # [win and py==38]

  patches:
    - patches/0001-relax-tolerence-in-special_math_test.patch                    # [linux]
    - patches/0002-skip-read-only-debugger_cli_common-test.patch                 # [linux]
    - patches/0003-relax-precision-in-matrix_log_op_test.patch                   # [linux]
    - patches/0004-Unbundle-LLVM.patch                                           # [linux]

build:
  number: 0
  skip: True  # [not x86_64]

requirements:
  build:
    - {{ compiler('c') }}       # [linux]
    - {{ compiler('cxx') }}     # [linux]
    - bazel                     # [linux]
    - nasm                      # [linux]
    - swig                      # [linux]
  host:
    # conda build requirements
    - python
    - pip
    #- setuptools <=39.1.0
    # requirements specified by the package itself
    - absl-py >=0.7.0
    - astor >=0.6.0
    - gast >=0.2.0
    - google-pasta >=0.1.6
    - keras-applications >=1.0.6
    - keras-preprocessing >=1.0.5
    - llvmdev >=9.0.0           # [linux]
    - zlib                      # [linux]
    - libpng                    # [linux]
    - libcurl                   # [linux]
    - unzip  # [linux]
    - zip  # [linux]
    - openjdk >=8  # [linux]
    - nsync  # [linux]
    - numpy >=1.16.1
    - six >=1.10.0
    - protobuf >=3.6.1
    - termcolor >=1.1.0
    - wrapt >=1.11.1
    - grpcio >=1.8.6
    - wheel >=0.26              # [linux]
    - tensorflow-estimator >=2.2.0,<2.3.0a0
  run:
    - {{ pin_subpackage('tensorflow-base', exact=True) }}

outputs:
  - name: tensorflow-base
    build:
      entry_points:
        - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
        - tflite_convert = tensorflow.lite.python.tflite_convert:main
        - toco = tensorflow.lite.python.tflite_convert:main
        - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
        # The tensorboard package adds this entry point.
        # - tensorboard = tensorboard.main:run_main
        - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
        - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      host:
        # conda build requirements
        - python
        - pip
        # requirements specified by the package itself
        - absl-py >=0.7.0
        - astor >=0.6.0
        - astunparse
        - gast >=0.2.0
        - google-pasta
        - h5py
        - keras-preprocessing >=1.0.5
        - numpy >=1.16.1
        - six >=1.10.0
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - wrapt >=1.11.1
        - grpcio >=1.8.6
        - wheel >=0.26              # [unix]
        - tensorflow-estimator >=2.2.0,<2.3.0a0
        - zlib  # [linux]
        - libpng  # [linux]
        - libcurl  # [linux]
      run:
        - python
        - absl-py >=0.7.0
        - astor >=0.6.0
        - astunparse
        - gast >=0.2.0
        - google-pasta
        - h5py
        - opt_einsum
        - keras-preprocessing >=1.0.5
        - {{ pin_compatible('numpy') }}
        - scipy
        - six >=1.10.0
        - protobuf >=3.6.1
        - termcolor >=1.1.0
        - wrapt >=1.11.1
        - grpcio >=1.8.6
        - tensorflow-estimator >=2.2.0,<2.3.0a0
        - tensorboard >=2.2.0,<2.3.0a0
    test:
      imports:
        - tensorflow
      commands:
        - freeze_graph --help
        - saved_model_cli --help
        - tflite_convert --help  # [not win]
        - toco_from_protos --help  # [not win]
        - toco --help  # [not win]

  - name: libtensorflow
    script: cp_libtensorflow.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]

    test:
      files:
        - test_c.c
      requires:
        - {{ compiler('c') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow.so  # [not win]
        - $CC -o test_c -L${PREFIX}/lib/ -ltensorflow -I${PREFIX}/include/ test_c.c && ./test_c  # [not win]

  - name: libtensorflow_cc
    script: cp_libtensorflow_cc.sh  # [unix]
    build:
      skip: true  # [not linux]
    requirements:
      # build requirements needs to pick up the compiler run_exports
      build:
        - {{ compiler('c') }}       # [linux]
        - {{ compiler('cxx') }}     # [linux]
      # host requirements to pick up run_exports
      host:
        - libcurl  # [linux]
        - zlib  # [linux]
      run:
        - libprotobuf >=3.6.1
        - nsync
    test:
      files:
        - test_cc.cc
      requires:
        - {{ compiler('cxx') }}
      commands:
        - test -f $PREFIX/lib/libtensorflow_cc.so  # [not win]
        - $CXX -std=c++11 -o test_cc -L${PREFIX}/lib/ -ltensorflow_cc -ltensorflow_framework -lrt -I${PREFIX}/include/ test_cc.cc && ./test_cc  # [not win]

about:
  home: http://tensorflow.org/
  license: Apache-2.0
  license_file: LICENSE
  license_family: Apache
  summary: TensorFlow is an open source machine learning framework for everyone.
  description: |
    TensorFlow provides multiple APIs.The lowest level API, TensorFlow Core
    provides you with complete programming control.
    Base package contains only tensorflow, not tensorflow-tensorboard.
  dev_url: https://github.com/tensorflow/tensorflow
  doc_url: https://www.tensorflow.org/get_started/get_started
  doc_source_url: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src

extra:
  recipe-maintainers:
    - waitingkuo
    - ghego
    - hajapy
    - gilbertfrancois
    - farhantejani
    - njzjz
    - jschueller
