package:
  name: tensorflow
  version: "0.12.1"

build:
  number: 2
  #  Google supplies whl files on PyPI for:
  # - Linux: Python 2.7, 3.3, 3.4, 3.5 and 3.6
  # - OS X: Python 2.7, 3.5 and 3.6
  # - Win-64: Python 3.5
  skip: True  # [win32]
  skip: True  # [win64 and not py35]
  skip: True  # [osx and py34]
  skip: True  # [py26]
  skip: True  # [py33]
  entry_points:
    - tensorboard = tensorflow.tensorboard.tensorboard:main

requirements:
  build:
    - python
    - pip
    - mock >=2.0.0
    - numpy >=1.11.0
    - protobuf ==3.1.0
    - six >=1.10.0
    - wheel >=0.26
  run:
    - python
    - mock >=2.0.0
    - numpy >=1.11.0
    - protobuf ==3.1.0
    - six >=1.10.0

test:
  imports:
    # Skip the import test on Linux as wheel file require a more recent
    # version of GLIBC++ than the VM used to build and test package.
    - tensorflow  # [not linux]

about:
  home: http://tensorflow.org/
  license: Apache 2.0
  summary: TensorFlow helps the tensors flow

extra:
  recipe-maintainers:
    - jjhelmus
    - danielfrg
    - waitingkuo
    - ghego
