travis:
  secure:
    BINSTAR_TOKEN: YKrpBFmRkuI5APwlRxK9ron2Mtu8S8cnkdKwo2HFnU8BFpWSRR6b8JLXsS+PH7o9jFViBPpVayk1GVEoI5Z+XkdFSNGxzT1NKhs+5dfgPFpoznIBpqSM0Z/pq9zC2oTQEnMj7OpJKpJBvUnLQPCIlPTUuxKjfZLrR2kszozJT3sG8EhpWXDZPBR8a7zGdUBIKeT81rzsKPZCSx6CrlrDZlBjReezm5mHS32dpFwyWPUeV32pWoho5vUJuqWtbEryywOiCgeEEejnt3sn2dB9J4pyZUxfEWEfnDTpFyx1h9Ze+HkwDdwN5WXx7XGeIMNcnjxSF2DegidMEnygnMt524mbwnVNIRNT0YyKEW2RqaE32HQoXsPK/ceidEZdMWd9KwgFiKgiDtoKkpwPXnpTYau1DbWKeCuYPKifNdHG9/b/lcy3bBmEXdpuz3LpZohVSF/wuXoV7gKhXNigATcobDrrxK0V0IaFlYA5TxhIbXKNjYlH1xBnuJ2QqUC7n9PSF65QcPsxradIQb2SzjI6QF3g6ahqofAgHXGeLKCOk+EeijzpYDbbSlsVTz7S/Tvuse+Gta/loWj0ozGWAouwsy0r9FR9E8+p1A5IBsmIxgLodtnYONYtyht/mVMIJBBFildDM39qTma2em0a2097Jh2YyNTdq2HwjcjPMecmxUQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
